# Set LANG ENV
language: node_js

node_js: stable

cache:
    directories:
        - node_modules

#
branches:
    only:
        - src

before_install:
    - npm install -g hexo-cli

install:
    - npm install

script:
    - hexo c
    - hexo g

after_script:
    - git config user.name "elia"
    - git config user.emai "jeannela@foxmail.com"
    - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
    - hexo d

#END: BUILD LifeCyle
